{% set name = "proteus" %}
{% set version = "1.7.3" %}
{% set build = 1 %}
{% set sha256 = "294b73d68b2a75d804105bc4f667e8db19d15677c9d86cb64d5a73948ecbeaa3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win or py2k]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - setuptools
    - cython
    - pip
    - daetk
    - hdf5 =1.10.5=*mpich*
    - metis
    - {{ mpi }}
    - numpy 1.14
    - openblas =0.3.7=*_7
    - parmetis
    - petsc4py
    - petsc 3.12
    - python 3
    - scorec
    - superlu
    - superlu_dist
    - triangle
    - pychrono
    - mpi4py
    - xtensor-python
  run:
    # This is an optional dependency
    # - gmsh        [not osx]
    - matplotlib
    - mpi4py
    - h5py =*=*mpich*
    - nose
    - pytables
    - pytest
    - pytest-xdist
    - scipy
    - tetgen
    - ncurses
    - pychrono
    - python 3
    - future
    - ipyparallel
    - pillow
    - recordtype
    - triangle
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('petsc4py', max_pin='x.x') }}
    - {{ pin_compatible('cython', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - proteus.clapack

about:
  home: http://proteustoolkit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc/proteus

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - zhang-alvin
