{% set name = "proteus" %}
{% set version = "1.8.0" %}
{% set build = 3 %}
{% set sha256 = "097cc8df364c7ec09f0e8ea3728f2fb2fce5df6a2789d3f17dfcaf1249e381da" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # [not linux]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - setuptools
    - cython
    - pip
    - daetk
    - metis
    - {{ mpi }}
    - numpy
    - openblas
    - parmetis
    - petsc4py
    - petsc
    - python 3
    - scorec
    - superlu
    - superlu_dist
    - triangle
    - pychrono
    - mpi4py
    - xtensor-python
    - eigen
    # need to list libnetcdf and netcdf-fortran twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
  run:
    # This is an optional dependency
    # - gmsh        [not osx]
    - matplotlib-base
    - mpi4py
    - nose
    - pytables
    - pytest
    - pytest-xdist
    - scipy
    - tetgen
    - ncurses
    - pychrono
    - python 3
    - future
    - ipyparallel
    - pillow
    - recordtype
    - triangle
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('petsc4py', max_pin='x.x') }}
    - {{ pin_compatible('cython', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    # need to list libnetcdf and netcdf-fortran twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*

test:
  imports:
    - proteus.clapack

about:
  home: http://proteustoolkit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc/proteus

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - zhang-alvin
    - jan-janssen
    - cekees
