{% set name = "proteus" %}
{% set version = "1.8.3" %}
{% set build = 2 %}
{% set sha256 = "315f0600044e2ad86592c248a9a4ca87dc58c1d678af2c27a9ddde802b555618" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - setuptools
    - cython >=3
    - pybind11
    - pip
    - metis
    - {{ mpi }}
    - numpy >=1.25.1
    - openblas
    - parmetis
    - petsc4py
    - petsc
    - python
    - scorec >=2.2.8
    - triangle
    - superlu
    - superlu_dist
    - pychrono >=9
    - mpi4py
    - xtensor-python
    - eigen
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
  run:
    - mpi4py
    - scipy
    - tetgen
    - triangle
    - ncurses
    - pychrono >=9
    - scorec >=2.2.8
    - python 3
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('petsc4py', max_pin='x.x') }}
    - {{ pin_compatible('cython', max_pin='x.x') }}
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - h5py
    - h5py * {{ mpi_prefix }}_*
test:
  imports:
    - proteus
  source_files:
    - test
  requires:
    - pytest
    - pytest-forked
    - matplotlib-base
  commands:
    - pytest -v test/ci/test_meshPartitionFromTetgenFiles.py

about:
  home: http://proteustoolkit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc/proteus

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - zhang-alvin
    - jan-janssen
    - cekees
