{% set name = "proteus" %}
{% set version = "1.8.2" %}
{% set build = 2 %}
{% set sha256 = "bd22a7dfac25977e8d040e4332e8013dd5088b1685fe22b0f4e31e6182a10a5a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # pychrono doens't have builds after Python 3.10
  skip: true  # [win or py>310]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - setuptools
    - cython >=3
    - pybind11
    - pip
    - daetk
    - metis
    - {{ mpi }}
    - numpy 1.25
    - openblas
    - parmetis >=4.0.3
    - petsc4py
    - petsc
    - python
    - scorec >=2.2.7
    - triangle
    - superlu
    - superlu_dist
    - pychrono
    - mpi4py
    - xtensor-python
    - eigen
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
  run:
    #for testing
    - matplotlib-base
    - pytest
    - pytest-xdist
    #
    - mpi4py
    - scipy
    - tetgen
    - ncurses
    - pychrono >=7
    - python 3
    - future
    - triangle
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('petsc4py', max_pin='x.x') }}
    - {{ pin_compatible('cython', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - h5py
    - h5py * {{ mpi_prefix }}_*
test:
  imports:
    - proteus
  requires:
    - pytest
  commands:
    - pytest -v --pyargs proteus.tests.ci.test_meshPartitionFromTetgenFiles

about:
  home: http://proteustoolkit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc/proteus

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - zhang-alvin
    - jan-janssen
    - cekees
