{% set name = "proteus" %}
{% set version = "1.7.1" %}
{% set build = 5 %}
{% set sha256 = "fa92cc384a83d6ad9ba3ce52aa4d8f7ed7624c97a597fd9faadfce553af5c9fe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: proteus-{{ version }}.tar.gz
  url: https://github.com/erdc/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # [not linux]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - setuptools
    - cython
    - daetk
    - hdf5 =*=*mpich*
    - metis
    - {{ mpi }}
    - numpy 1.14
    - openblas
    - parmetis
    - petsc4py
    - petsc 3.11
    - python 3
    - scorec
    - superlu
    - superlu_dist
    - triangle
    - pychrono
    - mpi4py
  run:
    # This is an optional dependency
    # - gmsh        [not osx]
    - matplotlib
    - mpi4py
    - h5py =*=*mpich*
    - nose
    - pytables
    - pytest
    - pytest-xdist
    - scipy
    - tetgen
    - ncurses
    - pychrono
    - python 3
    - future
    - ipyparallel
    - pillow
    - recordtype
    - triangle
    - {{ pin_compatible('openblas', max_pin='x.x') }}
    - {{ pin_compatible('petsc4py', max_pin='x.x') }}
    - {{ pin_compatible('cython', max_pin='x.x') }}

test:
  imports:
    - proteus

about:
  home: http://proteustoolkit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Proteus is a Python package for rapidly developing computer models and numerical methods.
  dev_url: https://github.com/erdc/proteus

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - martinRenou
